Name = "Axel Ariel Saravia"

[Contact]
Phone = "+54 9 3525503330"
Email = "axelarielsaravia@gmail.com"
Github = "AxelArielSaravia"
Codepen = "axelarielsaravia"
Linkedin = "axelarielsaravia"

[Location]
Current = "Colonia Caroya, Córdoba, Argentina"
Other = "Ciudad autónoma de Buenos Aires, Argentina"

Lenguages = [
  "Español (nativo)",
  "Ingles (B2)"
]

[[Education]]
Entity = "Universidad Nacional de Córdoba"
Location = "Córdoba, Córdona, Argentina"
Creadential = "Licenciatura en Composición Musical"
Started = "2016"
Ended = "2023"
Details = [
  """Tome cursos con compositores como Eleazar Garzon, \
  Ana Gabriela Yaya Aguilar, y Sergio P. N. Poblete Barbero.""",
  "De 2019 a 2020, fui asistente alumnp en la catedra de morfología musical.",
  "Obtuve experiencia y desarrollo de un amplio abanico de tecnicas compositivas individuales y colectivas."
]

[[Education]]
Entity = "Universidad Nacional de Córdoba"
Location = "Córdoba, Córdona, Argentina"
Creadential = "Licenciatura en Ciencias de la Computación"
Started = "2021"
Ended = "unfinish"
